"""Approved PTH Fausta light-theme design tokens."""

COLOR_PRIMARY = "#2563EB"
COLOR_PRIMARY_HOVER = "#1D4ED8"
COLOR_ACCENT = "#0EA5E9"
COLOR_SUCCESS = "#16A34A"
COLOR_WARNING = "#D97706"
COLOR_ERROR = "#DC2626"
COLOR_TEXT_PRIMARY = "#0F172A"
COLOR_TEXT_SECONDARY = "#64748B"
COLOR_BORDER = "#E2E8F0"
COLOR_BORDER_STRONG = "#CBD5E1"
COLOR_SURFACE = "#FFFFFF"
COLOR_PAGE_BACKGROUND = "#F8FAFC"
COLOR_ROW_SELECTED = "#E6F1FB"

SPACING_XS = 4
SPACING_SM = 8
SPACING_MD = 16
SPACING_LG = 24
SPACING_XL = 32

RADIUS_SM = 6
RADIUS_MD = 10
